[package]
name = "rysql-sql"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "SQL parsing, formatting and syntax highlighting for RySQL."

[dependencies]
syntect = { workspace = true }
sqlformat = { workspace = true }
tracing = { workspace = true }
